version: '3'  # version of compose format 

services:
  api-db:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        AZURE_STORAGE_KEY_ARG: ${AZURE_STORAGE_KEY}
        ENDPOINT_SUFFIX_ARG: ${ENDPOINT_SUFFIX}
        AZURE_STORAGE_ACCOUNT_ARG: ${AZURE_STORAGE_ACCOUNT}
        APP_MODULE_ARG: main:app
        PORT_ARG: ${API_PORT}
        BIND_ARG: 0.0.0.0
        WORKER_CLASS_ARG: uvicorn.workers.UvicornWorker
    environment:
      APP_MODULE: main:app
      PORT: ${API_PORT}
      BIND: ${HOST}:${API_PORT}
      WORKER_CLASS: uvicorn.workers.UvicornWorker
    ports:
      - 8000:${API_PORT}

  api-verify:
    build:
      context: ./api_verify
      dockerfile: Dockerfile
      args:
        AZURE_STORAGE_KEY_ARG: ${AZURE_STORAGE_KEY}
        ENDPOINT_SUFFIX_ARG: ${ENDPOINT_SUFFIX}
        AZURE_STORAGE_ACCOUNT_ARG: ${AZURE_STORAGE_ACCOUNT}
        PORT_ARG: ${API_PORT}
    environment:
      PORT: ${API_PORT}
    ports:
      - 8001:${API_PORT}
    depends_on:
      - api-db
