FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

ARG PY_VERSION=3.8

WORKDIR /api

COPY . /api

RUN python -m pip install --upgrade pip \
    && pip install -r requirements.txt \
    && find /usr/local/lib/python$PY_VERSION -name '*.c' -delete \
    && find /usr/local/lib/python$PY_VERSION -name '*.pxd' -delete \
    && find /usr/local/lib/python$PY_VERSION -name '*.pyd' -delete \
    && find /usr/local/lib/python$PY_VERSION -name '__pycache__' | xargs rm -r
