name: CI

on: [push, pull_request]

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Upgrade python-pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install tox
      - name: Run tests and Show test summary
        run: make tests
        env:
          HOST: 0.0.0.0
          API_PORT: 8050
          HOSTNAME: localhost
          POSTGRES_PORT: 5434
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          API_USER_NAME: anthony
          API_USER_PASSWORD: mysecret
          SHOW_COV_HTML: False
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./api/tests/test-logs/coverage.xml
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
          path_to_write_report: ./api/tests/test-logs/codecov_report.txt
          verbose: true
