name: CI

on: [push, pull_request]

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Upgrade python-pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install tox
      - name: Run tests
        run: make test
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
          ENDPOINT_SUFFIX: ${{ secrets.ENDPOINT_SUFFIX }}
      - name: Show test coverage HTML
        run: make show-cov-html
        env:
          SHOW_COV_HTML: False
      # - name: Upload coverage data to coveralls.io
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: coveralls
